export * from './defeats.model';
export * from './entity.model';
export * from './lizard.model';
export * from './outcome.model';
export * from './paper.model';
export * from './result.model';
export * from './rock.model';
export * from './scissors.model';
export * from './spock.model';
